POST http://localhost:3001/tasks/create
Content-Type: application/json

{
  "title": "Do laundry",
  "description": "Must have clean clothes",
  "status": "todo",
  "priority": "normal",
  "dueDate": "2026-01-01T12:00:00Z"
  
}