POST http://localhost:3001/tasks/create
Content-Type: application/json

{
  "title": "Eat breakfast",
  "description": "Most important meal of the day",
  "status": "todo",
  "priority": "normal",
  "dueDate": "2026-01-01T12:00:00Z"
  
}